export const docTableHead = [
  "Nome do documento",
  "Tipo de documento",
  "Última atualização",
  "Criado por:",
];

export const filterFieldData = [ 
  [ 'Rodrigo', 'Luiz', 'He', 'item 4'],
  [ 'Lu', 'item 2', 'item 3', 'item 4'],
  [ 'Maria', 'item 2', 'item 3', 'item 4'],
  [ 'Heitor', 'item 2', 'item 3', 'item 4'],
];

export const mockData = [
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Diego",
    documentType: "Carteira de Trabalho",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Lucia",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Lucas",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Natalia",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Daniela",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Heitor",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Luiz",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Elizabete",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
];
