export const COLUMNS = [
  { 
    Header: "Tipo ", 
    accessor: "type",
    disableFilters: true,
    minWidth: 60,
  },
  { 
    Header: "Tipo de consulta", 
    accessor: "portifolio_or_presignup",
  },
  { 
    Header: "CPF ou CNPJ", 
    accessor: "cpf_or_cnpj",
    textField: true 
  },
  { 
    Header: "Tipo de produtor", 
    accessor: "type_of_person",
  },
  { 
    Header: "Agroindústria", 
    accessor: "agroindustry",
    minWidth: 170
  },
  { 
    Header: "Produto", 
    accessor: "product",  
  },
  { 
    Header: "Garantia", 
    accessor: "guarantee",
    
  },
  { 
    Header: "Cultura", 
    accessor: "production",
  },
  { 
    Header: "Finalidade", 
    accessor: "destination",
  },
  { 
    Header: "Modalidade", 
    accessor: "modality",
  },
  { 
    Header: "Id_controle_taxa", 
    accessor: "id_tax",
    textField: true
  }
];

export const filterFieldData = [ 
  ['Presignup', 'Portifólio'],
  ['textInput'],
  ['F', 'J'],
  [ 'Avenorte','Bello', 'Coopeavi', 'Pluma', 'Plusval', 'Vigor'],
  ['Adequação', 'Custeio'],
  ['Tipo de garantia 1', 'Tipo de garantia 2'],
  ['Frango de corte', 'Leite', 'Suinocultura', 'Café', 'Cana-de-açúcar'],
  ['Finalidade 1', 'Finalidade 2'],
  ['Modalidade 1', 'Modalidade 2'],
  ['textInput']
];

export const mockData = [
  {
    portifolio_or_presignup: "Presignup",
    cpf_or_cnpj: "67564565789",
    type_of_person: "J",
    agroindustry: "Vigor",
    product: "Adequação",
    guarantee: "Estoque",
    production: "Leite",
    destination: "Bem-estar animal",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "22334565789",
    type_of_person: "F",
    agroindustry: "Coopeavi",
    product: "Custeio",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "08764565789",
    type_of_person: "F",
    agroindustry: "Bello",
    product: "Custeio",
    guarantee: "Tipo de garantia 3",
    production: "Frango Griller",
    destination: "Outros",
    modality: "Compra de Aquecedor",
    id_tax: "2dfd2"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "34534565789",
    type_of_person: "F",
    agroindustry: "Coopeavi",
    product: "Custeio",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Presignup",
    cpf_or_cnpj: "22434566549",
    type_of_person: "F",
    agroindustry: "Coopeavi",
    product: "Custeio",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "03434565789",
    type_of_person: "F",
    agroindustry: "Novamérica",
    product: "Custeio",
    guarantee: "Tipo de garantia 3",
    production: "Frango Griller",
    destination: "Outros",
    modality: "Compra de Aquecedor",
    id_tax: "2dfd2"
  },
  {
    portifolio_or_presignup: "Presignup",
    cpf_or_cnpj: "23423465789",
    type_of_person: "F",
    agroindustry: "Novamérica",
    product: "Custeio",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "14345657829",
    type_of_person: "F",
    agroindustry: "Coopeavi",
    product: "Custeio",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "03434565339",
    type_of_person: "F",
    agroindustry: "Avenorte",
    product: "Adequação",
    guarantee: "Tipo de garantia 3",
    production: "Frango Griller",
    destination: "Outros",
    modality: "Compra de Aquecedor",
    id_tax: "2dfd2"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "23434565789",
    type_of_person: "F",
    agroindustry: "Plusval",
    product: "Adequação",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Presignup",
    cpf_or_cnpj: "34034565789",
    type_of_person: "J",
    agroindustry: "Pluma",
    product: "Adequação",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "03434565789",
    type_of_person: "J",
    agroindustry: "Bello",
    product: "Custeio",
    guarantee: "Tipo de garantia 3",
    production: "Frango Griller",
    destination: "Outros",
    modality: "Compra de Aquecedor",
    id_tax: "2dfd2"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "223434565789",
    type_of_person: "J",
    agroindustry: "Pluma",
    product: "Adequação",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Presignup",
    cpf_or_cnpj: "23434565789",
    type_of_person: "J",
    agroindustry: "Vigor",
    product: "Custeio",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "03434565789",
    type_of_person: "J",
    agroindustry: "Bello",
    product: "Adequação",
    guarantee: "Tipo de garantia 3",
    production: "Frango Griller",
    destination: "Outros",
    modality: "Compra de Aquecedor",
    id_tax: "2dfd2"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "23434565789",
    type_of_person: "J",
    agroindustry: "Vigor",
    product: "Custeio",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Presignup",
    cpf_or_cnpj: "23434565789",
    type_of_person: "J",
    agroindustry: "Adequação",
    product: "Custeio",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "03434565789",
    type_of_person: "F",
    agroindustry: "Primaco",
    product: "Custeio",
    guarantee: "Tipo de garantia 3",
    production: "Frango Griller",
    destination: "Outros",
    modality: "Compra de Aquecedor",
    id_tax: "2dfd2"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "23434565789",
    type_of_person: "J",
    agroindustry: "Pluma",
    product: "Custeio",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Presignup",
    cpf_or_cnpj: "23434565789",
    type_of_person: "J",
    agroindustry: "Pluma",
    product: "Custeio",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "03434565789",
    type_of_person: "J",
    agroindustry: "Bello",
    product: "Custeio",
    guarantee: "Tipo de garantia 3",
    production: "Frango Griller",
    destination: "Outros",
    modality: "Compra de Aquecedor",
    id_tax: "2dfd2"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "23434565789",
    type_of_person: "J",
    agroindustry: "Pluma",
    product: "Adequação",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Presignup",
    cpf_or_cnpj: "23434565789",
    type_of_person: "F",
    agroindustry: "Pluma",
    product: "Adequação",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "03434565789",
    type_of_person: "F",
    agroindustry: "Adequação",
    product: "Custeio",
    guarantee: "Tipo de garantia 3",
    production: "Frango Griller",
    destination: "Outros",
    modality: "Compra de Aquecedor",
    id_tax: "2dfd2"
  },
  {
    portifolio_or_presignup: "Presignup",
    cpf_or_cnpj: "23434565789",
    type_of_person: "F",
    agroindustry: "Adequação",
    product: "Custeio",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "23434565789",
    type_of_person: "F",
    agroindustry: "Adequação",
    product: "Custeio",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "03434565789",
    type_of_person: "F",
    agroindustry: "Adequação",
    product: "Custeio",
    guarantee: "Tipo de garantia 3",
    production: "Frango Griller",
    destination: "Outros",
    modality: "Compra de Aquecedor",
    id_tax: "2dfd2"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "23434565789",
    type_of_person: "F",
    agroindustry: "Coopeavi",
    product: "Adequação",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Presignup",
    cpf_or_cnpj: "23434565789",
    type_of_person: "F",
    agroindustry: "Pluma",
    product: "Adequação",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "03434565789",
    type_of_person: "F",
    agroindustry: "Pluma",
    product: "Custeio",
    guarantee: "Tipo de garantia 3",
    production: "Frango Griller",
    destination: "Outros",
    modality: "Compra de Aquecedor",
    id_tax: "2dfd2"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "23434565789",
    type_of_person: "F",
    agroindustry: "Coopeavi",
    product: "Custeio",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "23434565789",
    type_of_person: "F",
    agroindustry: "Pluma",
    product: "Adequação",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Presignup",
    cpf_or_cnpj: "03434565789",
    type_of_person: "F",
    agroindustry: "Bello",
    product: "Adequação",
    guarantee: "Tipo de garantia 3",
    production: "Frango Griller",
    destination: "Outros",
    modality: "Compra de Aquecedor",
    id_tax: "2dfd2"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "23434565789",
    type_of_person: "F",
    agroindustry: "Novamérica",
    product: "Adequação",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "23434565789",
    type_of_person: "F",
    agroindustry: "Plusval",
    product: "Adequação",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "03434565789",
    type_of_person: "F",
    agroindustry: "Vigor",
    product: "Custeio",
    guarantee: "Tipo de garantia 3",
    production: "Frango Griller",
    destination: "Outros",
    modality: "Compra de Aquecedor",
    id_tax: "2dfd2"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "23434565789",
    type_of_person: "F",
    agroindustry: "Vigor",
    product: "Custeio",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "23434565789",
    type_of_person: "F",
    agroindustry: "Coopeavi",
    product: "Adequação",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "03434565789",
    type_of_person: "F",
    agroindustry: "Novamérica",
    product: "Custeio",
    guarantee: "Tipo de garantia 3",
    production: "Frango Griller",
    destination: "Outros",
    modality: "Compra de Aquecedor",
    id_tax: "2dfd2"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "23434565789",
    type_of_person: "F",
    agroindustry: "Pluma",
    product: "Adequação",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "23434565789",
    type_of_person: "F",
    agroindustry: "Pluma",
    product: "Custeio",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "03434565789",
    type_of_person: "F",
    agroindustry: "Plusval",
    product: "Custeio",
    guarantee: "Tipo de garantia 3",
    production: "Frango Griller",
    destination: "Outros",
    modality: "Compra de Aquecedor",
    id_tax: "2dfd2"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "23434565789",
    type_of_person: "F",
    agroindustry: "Coopeavi",
    product: "Custeio",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "23434565789",
    type_of_person: "F",
    agroindustry: "Pluma",
    product: "Custeio",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "03434565789",
    type_of_person: "F",
    agroindustry: "Pluma",
    product: "Custeio",
    guarantee: "Tipo de garantia 3",
    production: "Frango Griller",
    destination: "Outros",
    modality: "Compra de Aquecedor",
    id_tax: "2dfd2"
  },
  {
    portifolio_or_presignup: "Portifólio",
    cpf_or_cnpj: "23434565789",
    type_of_person: "F",
    agroindustry: "Pluma",
    product: "Custeio",
    guarantee: "Tipo de garantia 1",
    production: "Frango de corte",
    destination: "Finalidade 1",
    modality: "Modalidade 1",
    id_tax: "2342"
  },
]; 

export const headersCSV = [
  {label: 'Tipo de Consulta', key: 'portifolio_or_presignup'},
  {label: 'CPF ou CNPJ', key: 'cpf_or_cnpj'},
  {label: 'Tipo de Produtor', key: 'type_of_person'},
  {label: 'Agroindústria', key: 'agroindustry'},
  {label: 'Produto', key: 'product'},
  {label: 'Garantia', key: 'guarantee'},
  {label: 'Cultura', key: 'production'},
  {label: 'Finalidade', key: 'destination'},
  {label: 'Modalidade', key: 'modality'},
  {label: 'id Controle Taxa', key: 'id_tax'},
]