export const docTableHead = [
  "Nome do documento",
  "Tipo de documento",
  "Última atualização",
  "Criado por:",
];

export const mockData = [
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
  {
    documentName: "Rodrigo",
    documentType: "Cpf",
    timestamp: "13/12/2022",
    createdBy: "João",
  },
];
